# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_title', models.CharField(max_length=20)),
                ('sale_description', models.TextField(max_length=50)),
                ('url', models.SlugField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.IntegerField(choices=[(1, 'Ahvenanmaa'), (2, 'Etelä Karjala'), (3, 'Etelä Pohjanmaa'), (4, 'Etelä Savo'), (5, 'Itä Uusimaa'), (6, 'Kainuu'), (7, 'Kanta Häme'), (8, 'Keski Pohjanmaa'), (9, 'Keski Suomi'), (10, 'Kymenlaakso'), (11, 'Lappi'), (12, 'Pirkanmaa'), (13, 'Pohjanmaa'), (14, 'Pohjois Karjala'), (15, 'Pohjois Pohjanmaa'), (16, 'Pohjois Savo'), (17, 'Päijät Häme'), (18, 'Satakunta'), (19, 'Uusimaa'), (20, 'Varsinais Suomi')], default=1)),
                ('category', models.IntegerField(choices=[(1, 'Groceries'), (2, 'Household Items'), (3, 'Furnitures'), (4, 'Meals'), (5, 'Electronic'), (6, "Women's Clothing"), (7, "Men's Clothing"), (8, "Kids's Clothing"), (9, 'Keski-Suomi'), (10, 'Automotive'), (11, 'Fishing'), (12, 'Housing')], default=1)),
                ('address', models.CharField(default='', max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
