# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Banners/users.User/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Groceries'), (2, 'Household Items'), (3, 'Furnitures'), (4, 'Meals'), (5, 'Electronic'), (6, "Women's Clothing"), (7, "Men's Clothing"), (8, "Kids's Clothing"), (9, 'Automotive'), (10, 'Fishing'), (11, 'Housing')], default=1),
        ),
    ]
