# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advat', '0004_auto_20160218_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Media/YYYY/MM/DD/'),
        ),
    ]
