# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 15:06
from __future__ import unicode_literals

import advat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advat', '0005_auto_20160218_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=advat.models.file_upload_name),
        ),
    ]
