# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 15:09
from __future__ import unicode_literals

import advat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advat', '0006_auto_20160218_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to=advat.models.file_upload_name),
        ),
    ]
