# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advat', '0007_auto_20160218_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[('Groceries', 'Groceries'), (2, 'Household Items'), (3, 'Furnitures'), (4, 'Meals'), (5, 'Electronic'), (6, "Women's Clothing"), (7, "Men's Clothing"), (8, "Kids's Clothing"), (9, 'Automotive'), (10, 'Fishing'), (11, 'Housing')], default=1),
        ),
    ]
