# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advat', '0008_auto_20160218_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(100, 'Groceries'), (200, 'Household Items'), (300, 'Furnitures'), (400, 'Meals'), (500, 'Electronic'), (600, "Women's Clothing"), (700, "Men's Clothing"), (800, "Kids's Clothing"), (900, 'Automotive'), (1100, 'Fishing'), (1200, 'Housing')], default=1),
        ),
    ]
